---
baseURL: "https://transportcopy.com/"
title: "Transport Copy"
languageCode: "en-us"
metaDataFormat: yaml
pluralizeListTitles: false
enableRobotsTXT: true

permalinks:
  work: /:section/:slug/

taxonomies:
  tags: tags

params:
  CopyrightHTML: "Copyright &#xA9; 2019 Transport Copy Ltd"

menu:
  main:
    - Name: "About"
      Weight: 1
      Identifier: "about"
      URL: "/about/"
    - Name: "Previous Work"
      Weight: 2
      Identifier: "work"
      URL: "/work/"
    - Name: "Contact Me"
      Weight: 3
      Identifier: "contact"
      URL: "/contact/"
---
