---
baseURL: "https://transportcopy.com/"
title: "Transport Copy"
languageCode: "en-us"
metaDataFormat: yaml
pluralizeListTitles: false
enableRobotsTXT: true

permalinks:
  portfolio: /:section/:slug/

taxonomies:
  tags: tags

params:
  CopyrightHTML: "Copyright &#xA9; 2019 Transport Copy LLC"

menu:
  main:
    - Name: "Services/Rates"
      Weight: 1
      Identifier: "services"
      URL: "/services/"
    - Name: "About"
      Weight: 2
      Identifier: "about"
      URL: "/about/"
    - Name: "Portfolio"
      Weight: 3
      Identifier: "portfolio"
      URL: "/portfolio/"
    - Name: "Contact"
      Weight: 4
      Identifier: "contact"
      URL: "/contact/"
---
