backend:
  name: git-gateway
  branch: master

media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images


collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Button Text", name: "button_text", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "about"
        label: "About Me"
        file: "content/about/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "work"
        label: "Previous Work"
        file: "content/work/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "contact"
        label: "Contact"
        file: "content/contact/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "work"
    label: "Work"
    folder: "content/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Author", name: "author", widget: "string", default: "Sharon Beckstrand" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Link Only?", name: "link_only", widget: "boolean" }
      - { label: "Hero Image", name: "hero_src", widget: "image", default: "http://via.placeholder.com/500x280" }
      - { label: "Body", name: "body", widget: "markdown" }
