backend:
  name: git-gateway
  branch: master

media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images


collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Sub-headline", name: "subheadline", widget: "string" }
          - { label: "Button Text", name: "button_text", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
      - name: "services"
        label: "Services"
        file: "content/services/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_src", widget: "image", default: "http://via.placeholder.com/750x300" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
      - name: "about"
        label: "About Me"
        file: "content/about/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_src", widget: "image", default: "http://via.placeholder.com/750x300" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
      - name: "portfolio"
        label: "Portfolio"
        file: "content/portfolio/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
      - name: "contact"
        label: "Contact"
        file: "content/contact/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "slug", widget: "string", required: false }
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Author", name: "author", widget: "string", default: "Sharon Beckstrand" }
      - { label: "Description", name: "description", widget: "markdown", required: false }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Link Only?", name: "link_only", widget: "boolean", required: false }
      - { label: "Hero Image", name: "hero_src", widget: "image", default: "http://via.placeholder.com/500x280", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "config"
    label: "Config"
    files:
      - name: "siteconfig"
        label: "Site Config"
        file: "/data/siteconfig.yaml"
        fields:
          - { label: "Copyright", name: "CopyrightHTML", widget: "string" }
